name: Build and Release Cube

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4.1.1

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build Cube (Linux AMD64)
        run: |
          go mod tidy
          TAG_NAME="${GITHUB_REF_NAME}"
          BUILD_TIME=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          echo "Building with ldflags:"
          echo "-X github.com/pariskwsto/cube/build.Version=${TAG_NAME}"
          echo "-X github.com/pariskwsto/cube/build.User=${GITHUB_ACTOR}"
          echo "-X github.com/pariskwsto/cube/build.Time=${BUILD_TIME}"
          echo "-X github.com/pariskwsto/cube/build.GitCommit=${GITHUB_SHA}"
          env GOOS=linux GOARCH=amd64 go build -ldflags "-X github.com/pariskwsto/cube/build.Version=${TAG_NAME} -X github.com/pariskwsto/cube/build.User=${GITHUB_ACTOR} -X github.com/pariskwsto/cube/build.Time=${BUILD_TIME} -X github.com/pariskwsto/cube/build.GitCommit=${GITHUB_SHA}" -o cube-linux-amd64 main.go

      - name: Create GitHub Release & Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          files: cube-linux-amd64
          tag_name: ${{ github.ref_name }}
          name: "cube ${{ github.ref_name }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.CUBE_PAT }}